version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
